"""Revision 2

Revision ID: 3220e74b1c5a
Revises: e0d230c1cd8b
Create Date: 2026-03-02 19:24:50.025365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3220e74b1c5a'
down_revision: Union[str, Sequence[str], None] = 'e0d230c1cd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
