"""Revision 6

Revision ID: 4ebe1239e892
Revises: c6a9bfae1626
Create Date: 2026-03-09 20:09:04.358610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebe1239e892'
down_revision: Union[str, Sequence[str], None] = 'c6a9bfae1626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
