"""Revision 4

Revision ID: 914ce8cfa3ab
Revises: 47dc4ea5a0d8
Create Date: 2026-03-05 20:25:39.042022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914ce8cfa3ab'
down_revision: Union[str, Sequence[str], None] = '47dc4ea5a0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
