"""Revision 8

Revision ID: 9a9a69c8977c
Revises: ff5ef6bf1204
Create Date: 2026-03-25 18:06:37.240419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9a69c8977c'
down_revision: Union[str, Sequence[str], None] = 'ff5ef6bf1204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('documents', sa.Column('language', sa.String(), nullable=True))

    op.execute("UPDATE documents SET language = 'en'")

    op.alter_column('documents', 'language', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'language')
    # ### end Alembic commands ###
