"""Revision 9

Revision ID: c614149c6f97
Revises: 9a9a69c8977c
Create Date: 2026-03-25 18:32:02.043266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c614149c6f97'
down_revision: Union[str, Sequence[str], None] = '9a9a69c8977c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('dialogs_user_id_fkey'), 'dialogs', type_='foreignkey')
    op.create_foreign_key(None, 'dialogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_dialog_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'dialogs', ['dialog_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_chunk_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'document_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_chunk_id_fkey'), 'embeddings', 'document_chunks', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_dialog_id_fkey'), 'documents', 'dialogs', ['dialog_id'], ['id'])
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'dialogs', type_='foreignkey')
    op.create_foreign_key(op.f('dialogs_user_id_fkey'), 'dialogs', 'users', ['user_id'], ['id'])
    op.alter_column('dialogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
